#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts


/usr/libexec/xdg-desktop-portal &
/usr/libexec/polkit-gnome-authentication-agent-1 &

# notification daemon
dunst &

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
$scripts/wall ~/.config/hypr/wallpapers/default &


dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
notify-send -a aurora "Hi there, $(whoami)" &
