#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

/usr/libexec/polkit-gnome-authentication-agent-1 &
/usr/bin/gnome-keyring-daemon --replace --daemonize --components=pkcs11,secrets,ssh &

# notification daemon
dunst &

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
$scripts/wall ~/.config/hypr/wallpapers/default &


dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
notify-send -a aurora "Hi there, $(whoami)" &
